#!/usr/bin/perl

use strict;
use warnings;

BEGIN {
  my $libPath = $0;
  $libPath =~ s!/?elymas$!!;
  push @INC, $libPath;
}

use Data::Dumper;
# $Data::Dumper::Deparse = 1;

use Elymas;
use ElymasGlobal;

executeFile($ARGV[0], [], \$ElymasGlobal::global);
